--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.8) ~  Much Love, Ferib 

]]--

local v0={"Are you a magician? Because whenever I look at you, everyone else disappears.","Do you have a map? I keep getting lost in your eyes.","Are you French? Because Eiffel for you.","Are you a campfire? Because you’re hot and I want s’more.","Do you have a Band-Aid? Because I just scraped my knee falling for you.","Are you a time traveler? Because I see you in my future.","Do you have a sunburn, or are you always this hot?","Is your dad a boxer? Because you’re a knockout!","Are you a snowstorm? Because you make my heart race.","Can I follow you home? Cause my parents always told me to follow my dreams.","Are you a camera? Because every time I look at you, I smile.","Are you an angel? Because heaven is missing one.","Is it hot in here or is it just you?","Can you lend me a pencil? Because I want to draw a smile on your face.","Do you know if there are any Wi-Fi signals around here? Because I’m feeling a connection.","Is your name Chapstick? Because you’re da balm!","Are you a dictionary? Because you add meaning to my life.","Do you have a pencil? Because I want to erase your past and write our future.","Do you have a quarter? Because I want to call my mom and tell her I met ‘The One’."};_G.rizzEnabled= not _G.rizzEnabled;if _G.rizzEnabled then game.StarterGui:SetCore("SendNotification",{Title="Rizz Loaded",Text="🎭  Hexploit 🎭",Duration=1070 -(68 + 997) });local function v1() local v4=math.random(1271 -(226 + 1044) , #v0);local v5=v0[v4];print("Sending rizz: "   .. v5 );local v6=game:GetService("TextChatService");local v7=v6.ChatInputBarConfiguration.TargetTextChannel;if (v6.ChatVersion==Enum.ChatVersion.LegacyChatService) then local v10=0 -0 ;local v11;while true do if (v10==0) then v11=game:GetService("ReplicatedStorage"):FindFirstChild("DefaultChatSystemChatEvents");if v11 then v11.SayMessageRequest:FireServer(v5,"All");end break;end end elseif v7 then v7:SendAsync(v5);else print("Chat system not available.");end end local v2=game:GetService("UserInputService");_G.rizzkeylistener=v2.InputBegan:Connect(function(v8,v9) if ( not v9 and (v8.KeyCode==Enum.KeyCode.T) and _G.rizzEnabled) then v1();end end);else local v3=117 -(32 + 85) ;while true do if (v3==(0 + 0)) then game.StarterGui:SetCore("SendNotification",{Title="Rizz Unloaded",Text="🎭  Hexploit 🎭",Duration=5});if _G.rizzkeylistener then _G.rizzkeylistener:Disconnect();_G.rizzkeylistener=nil;end break;end end end
